### PR TITLE
Package as a command line script for Pypi

### PR DESCRIPTION
**Pull request by dedan**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/jupyter-linter/3)

### CODE REVIEW

**Comment by dedan** [comment]
@akegan @ericboucher @tetraptych 

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/jupyter-linter/3#-:-Kh9_zVQ8nYIDl2F2ZFt:b-w7stev)*

**Comment by pcorpet** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[.gitignore, line 90 at r1](https://reviewable.io:443/reviews/bayesimpact/jupyter-linter/3#-KhBa-dgCBKxcOzUj1sG:-KhBa-dgCBKxcOzUj1sH:bonkobr) ([raw file](https://github.com/bayesimpact/jupyter-linter/blob/302d9d003b469e12939e105bcd87e196edcee41b/.gitignore#L90)):*
> ```
> # Rope project settings
> .ropeproject
> .DS_Store
> ```

please add a trailing line return

---

*[README.md, line 8 at r1](https://reviewable.io:443/reviews/bayesimpact/jupyter-linter/3#-KhBa6RbxjjElEdJesf7:-KhBa6RbxjjElEdJesf8:bsvsuvb) ([raw file](https://github.com/bayesimpact/jupyter-linter/blob/302d9d003b469e12939e105bcd87e196edcee41b/README.md#L8)):*
> ```Markdown
> 
> ```
> pip install jupyter-linter
> ```

That sounds like a pretty generic name for a linter that enforces Bayes Style Guide.

---

*[README.md, line 20 at r1](https://reviewable.io:443/reviews/bayesimpact/jupyter-linter/3#-KhBaigVn4riMqRpFY3T:-KhBaigVn4riMqRpFY3U:b-vkxicz) ([raw file](https://github.com/bayesimpact/jupyter-linter/blob/ff5bd9e8134a66f6f6b3f2a5a44482f0ef9b4b8b/README.md#L20)):*
> ```Markdown
> 
> TODO: Improve README by adding motivation for the project and better usage instructions.
> TODO: Package for easy distribution via Pypi and add instructions of how to publish to Pypi.
> ```

Please add instructions int he README how to publish a new version (I guess that it includes updating the version number as well as running `setup.py publish`). Ideally you would also push releasers to tag the repo with the new version number as well.

---

*[setup.py, line 20 at r1](https://reviewable.io:443/reviews/bayesimpact/jupyter-linter/3#-KhBaZZbxt3Nkr_8HhFI:-KhBaZZbxt3Nkr_8HhFJ:bpg18gh) ([raw file](https://github.com/bayesimpact/jupyter-linter/blob/302d9d003b469e12939e105bcd87e196edcee41b/setup.py#L20)):*
> ```Python
> setuptools.setup(
>     name='jupyter-linter',
>     description='A simple linter to enforce the rules of our style guide https://goo.gl/lhK4JT.',
> ```

Again, "our" might be a bit generic for PyPi

---

*[jupyter_linter/__init__.py, line 1 at r1](https://reviewable.io:443/reviews/bayesimpact/jupyter-linter/3#-KhBaNhFwGz96YT_Z517:-KhBaNhFwGz96YT_Z518:b-vjcz4u) ([raw file](https://github.com/bayesimpact/jupyter-linter/blob/302d9d003b469e12939e105bcd87e196edcee41b/jupyter_linter/__init__.py#L1)):*
> ```Python
> from .jupyter_linter import main
> ```

I recommend not to use relative import, instead I suggest that you rename the file itself to `jupyter_linter/__init__.py`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/jupyter-linter/3)*

**Comment by dedan** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[jupyter_linter/__init__.py, line 1 at r1](https://reviewable.io:443/reviews/bayesimpact/jupyter-linter/3#-KhBaNhFwGz96YT_Z517:-KhDpRT8DYZwrwUvDnW5:byuyvr6) ([raw file](https://github.com/bayesimpact/jupyter-linter/blob/302d9d003b469e12939e105bcd87e196edcee41b/jupyter_linter/__init__.py#L1)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

I recommend not to use relative import, instead I suggest that you rename the file itself to `jupyter_linter/__init__.py`
</blockquote></details>

Sorry, I don't understand this comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/jupyter-linter/3)*

**Comment by pcorpet** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[jupyter_linter/__init__.py, line 1 at r1](https://reviewable.io:443/reviews/bayesimpact/jupyter-linter/3#-KhBaNhFwGz96YT_Z517:-KhGUphYl8fk6WRSa0HX:bbvq5lw) ([raw file](https://github.com/bayesimpact/jupyter-linter/blob/302d9d003b469e12939e105bcd87e196edcee41b/jupyter_linter/__init__.py#L1)):*
<details><summary><i>Previously, dedan (Stephan Gabler) wrote…</i></summary><blockquote>

Sorry, I don't understand this comment.
</blockquote></details>

I thought you were adding this file so that `main` is accessible directly by using
```py
import jupyter_linter

jupyter_linter.main()
```

To do that you use an import that starts with a dot, which for me is a "relative" import (relative to the current file).

My feeling is that you do not need two files and can actually have the whole content of the linter directly in the `__init__.py` file, and drop the `jupyter_linter/jupyter_linter.py` file altogether. See what I did in https://github.com/bayesimpact/python-emploi-store/tree/master/emploi_store

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/jupyter-linter/3)*

**Comment by dedan** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[.gitignore, line 90 at r1](https://reviewable.io:443/reviews/bayesimpact/jupyter-linter/3#-KhBa-dgCBKxcOzUj1sG:-KhPOsraB3YaoVt5gMDH:b-896fix) ([raw file](https://github.com/bayesimpact/jupyter-linter/blob/302d9d003b469e12939e105bcd87e196edcee41b/.gitignore#L90)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

please add a trailing line return
</blockquote></details>

Done.

---

*[README.md, line 8 at r1](https://reviewable.io:443/reviews/bayesimpact/jupyter-linter/3#-KhBa6RbxjjElEdJesf7:-KhPPPXXw8gwpg0n4amh:b-896fix) ([raw file](https://github.com/bayesimpact/jupyter-linter/blob/302d9d003b469e12939e105bcd87e196edcee41b/README.md#L8)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

That sounds like a pretty generic name for a linter that enforces Bayes Style Guide.
</blockquote></details>

Done.

---

*[README.md, line 20 at r1](https://reviewable.io:443/reviews/bayesimpact/jupyter-linter/3#-KhBaigVn4riMqRpFY3T:-KhPPm5h4i0QPnKipCRV:b-896fix) ([raw file](https://github.com/bayesimpact/jupyter-linter/blob/ff5bd9e8134a66f6f6b3f2a5a44482f0ef9b4b8b/README.md#L20)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Please add instructions int he README how to publish a new version (I guess that it includes updating the version number as well as running `setup.py publish`). Ideally you would also push releasers to tag the repo with the new version number as well.
</blockquote></details>

Done.

---

*[setup.py, line 20 at r1](https://reviewable.io:443/reviews/bayesimpact/jupyter-linter/3#-KhBaZZbxt3Nkr_8HhFI:-KhPPoMvbFKBzbAdRMGJ:b-896fix) ([raw file](https://github.com/bayesimpact/jupyter-linter/blob/302d9d003b469e12939e105bcd87e196edcee41b/setup.py#L20)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Again, "our" might be a bit generic for PyPi
</blockquote></details>

Done.

---

*[jupyter_linter/__init__.py, line 1 at r1](https://reviewable.io:443/reviews/bayesimpact/jupyter-linter/3#-KhBaNhFwGz96YT_Z517:-KhPQCombmwydxYwWjFp:b-wz4duo) ([raw file](https://github.com/bayesimpact/jupyter-linter/blob/302d9d003b469e12939e105bcd87e196edcee41b/jupyter_linter/__init__.py#L1)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

I thought you were adding this file so that `main` is accessible directly by using
```py
import jupyter_linter

jupyter_linter.main()
```

To do that you use an import that starts with a dot, which for me is a "relative" import (relative to the current file).

My feeling is that you do not need two files and can actually have the whole content of the linter directly in the `__init__.py` file, and drop the `jupyter_linter/jupyter_linter.py` file altogether. See what I did in https://github.com/bayesimpact/python-emploi-store/tree/master/emploi_store
</blockquote></details>

Done. I left a TODO.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/jupyter-linter/3)*

**Comment by pcorpet** [comment]
:lgtm:

---

Reviewed 1 of 8 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 29 at r2](https://reviewable.io:443/reviews/bayesimpact/jupyter-linter/3#-KhQyomSckX0cX4tpxzg:-KhQyomSckX0cX4tpxzh:b-tt08o2) ([raw file](https://github.com/bayesimpact/jupyter-linter/blob/b110a7711ce203758ee2cac955c2161661a0bfab/README.md#L29)):*
> ```Markdown
> 1. Update the version number in `setup.py`.
> 2. Run `python setup.py publish`.
> ```

3. Run `git tag <new version number>`.

---

*[setup.py, line 23 at r2](https://reviewable.io:443/reviews/bayesimpact/jupyter-linter/3#-KhQz5lZmwih-ic1ol4y:-KhQz5lZmwih-ic1ol4z:b-l7seqa) ([raw file](https://github.com/bayesimpact/jupyter-linter/blob/b110a7711ce203758ee2cac955c2161661a0bfab/setup.py#L23)):*
> ```Python
>     description=(
>         'A simple linter to enforce the rules of the Bayes Impact '
>         'style guide https://goo.gl/lhK4JT.'),
> ```

nit - Style Guide (to be consistent with the rest of the comments).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/jupyter-linter/3#-:-KhQzAk4sjAonFY2EXNl:bnfp4nl)*

**Pull request merged**
