### PR TITLE
Add linting and automated testing on CircleCi Remove empty line First rough version of the Jupyter Linter.

### PR DESCRIPTION
**Pull request by dedan**
See the README of how to run and test it.

---
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/jupyter-linter/2)

### CODE REVIEW

**Comment by dedan** [comment]
@ericboucher @akegan @tetraptych Please only from r2 on.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/jupyter-linter/2#-:-Kh3dPgZtzGnbyixKpQe:blbrou8)*

**Comment by akegan** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/jupyter-linter/2#-:-Kh3e3Fig5-7heIpxiMN:bnfp4nl)*

**Comment by pcorpet** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[circle.yml, line 3 at r4](https://reviewable.io:443/reviews/bayesimpact/jupyter-linter/2#-Kh6jEblO76GcqoTOYNs:-Kh6jEblO76GcqoTOYNt:be0zmm1) ([raw file](https://github.com/bayesimpact/jupyter-linter/blob/6ce28b0e7ad9793937923e5770bec0c4f9706945/circle.yml#L3)):*
> ```YAML
> dependencies:
>   pre:
>     - pip install -r requirements.txt
> ```

Nit - Is that needed? I thought that CircleCI would detect that automatically.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/jupyter-linter/2#-:-Kh6jIazOQDoHnYno0b4:bnfp4nl)*

**Comment by dedan** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[circle.yml, line 3 at r4](https://reviewable.io:443/reviews/bayesimpact/jupyter-linter/2#-Kh6jEblO76GcqoTOYNs:-Kh8gLuC3h2pY6U5Qt3g:b-en5ysr) ([raw file](https://github.com/bayesimpact/jupyter-linter/blob/6ce28b0e7ad9793937923e5770bec0c4f9706945/circle.yml#L3)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Nit - Is that needed? I thought that CircleCI would detect that automatically.
</blockquote></details>

Done. Nice, I didn't know that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/jupyter-linter/2)*

**Pull request merged**
